services:
  db:
    image: postgres:16
    container_name: isitlive-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: isitlive
      POSTGRES_USER: postgress
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
